version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: mtls-api
    expose:
      - "8080"

  gateway:
    image: nginx:1.27.0-alpine
    container_name: mtls-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./certs/server.key:/etc/nginx/certs/server.key:ro
      - ./certs/ca.crt:/etc/nginx/certs/ca.crt:ro
    ports:
      - "8443:443"
    depends_on:
      - api